spring:
  application:
    name: spring-boot-seckill
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost
    port: 6379
    password: 123456
server:
  port: 8081